In [7]:
# from google.colab import drive
# drive.mount('/content/drive/')

In [8]:
# cd /content/drive/MyDrive/Projects/TorchTutorial/chap02

In [9]:
import torch
import numpy as np

In [10]:
temp = torch.tensor([[1,2],[3,4]])

In [11]:
temp.numpy()

array([[1, 2],
       [3, 4]])

In [12]:
# temp = torch.tensor([[1,2],[3,4]], device = 'cuda:0')

In [13]:
temp.to('cpu').numpy()

array([[1, 2],
       [3, 4]])

In [14]:
temp = torch.FloatTensor([1,2,3,4,5,6,7])

In [15]:
temp[4:-1]

tensor([5., 6.])

In [16]:
v = torch.tensor([1,2,3])
w = torch.tensor([3,4,6])

print(w - v)

tensor([2, 2, 3])


In [17]:
# class CustomDataset(torch.utils.data.Dataset):
#     def __init__(self): --- 필요한 변수를 선언하고, 데이터셋의 전처리를 해 주는 함수
#     def __len__(self): --- 데이터셋의 길이. 즉, 총 샘플의 수를 가져오는 함수
#     def __getitem__(self,index): --- 데이터셋에서 특정 데이터를 가져오는 함수 (index번째 데이터를 반환하는 함수이며, 이때 반환되는 값은 텐서의 형태를 취해야함)

In [18]:
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader

In [19]:
# class CustomDataset(Dataset):
#     def __init__(self, csv_file):
#         self.label = pd.read_csv(csv_file)

#     def __len__(self):
#         return len(self.label)

#     def __getitem__(self, idx):
#         sample = torch.tensor(self.label.iloc[idx, 0:3]).int()
#         label = torch.tensor(self.label.iloc[idx,3]).int()
#         return sample, label

# tensor_dataset = CustomDataset('../covtype.csv')
# dataset = DataLoader(tensor_dataset, batch_size = 4, shuffle = True)

In [20]:
import torchvision.transforms as transforms

In [21]:
mnist_transform = transforms.Compose([transforms.ToTensor(),
                                      transforms.Normalize((0.5,),(1,))])

In [22]:
# from torchvision.datasets import MNIST
# import requests

# download_root = './data/MNIST_DATASET'


# train_dataset = MNIST(download_root, transform = mnist_transform, train = True, download = True)

# valid_dataset = MNIST(download_root, transform = mnist_transform, train = False, download = True)

# test_dataset = MNIST(download_root, transform = mnist_transform, train = False, download = True)


In [23]:
import torch.nn as nn

class MLP(nn.Module):
    def __init__(self):
        super(MLP,self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(in_channels=3, out_channels=64, kernel_size=5),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2))

        self.layer2 = nn.Sequential(
            nn.Conv2d(in_channels=64, out_channels=30, kernel_size=5),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2))

        self.layer3 = nn.Sequential(
            nn.Linear(in_features= 30*5*5, out_features=10, bias = True),
            nn.ReLU(inplace=True))
        
    def forward(self,x) :
        x = self.layer1(x)
        x = self.layer2(x)
        x = x.view(x.shape[0], -1)
        x = self.layer3(x)
        return x

model = MLP()

print(list(model.children()))
print(list(model.modules()))

[Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)]
[MLP(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer3): Sequential(
    (0): Linear(in_features=750, out_features=10, bias=True)
    (1): ReLU(inplace=True)
  )
), Sequential(
  (0)

In [24]:
# from torch.optim import optimizer

# criterion = torch.nn.MSELoss()
# optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum = 0.9)
# scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer=optimizer, lr_lambda=lambda epoch: 0.95 ** epoch)

# for epoch in range(1, 100+1):
#     for x,y in dataloader:
#         optimizer.zero_grad()

# loss_fn(model(x),y).backward()
# optimizer.step()
# scheduler.step()

In [25]:
# for epoch in range(100):
#     yhat = model(x_train)
#     loss = criterion(yhat, y_train)
#     optimizer.zero_grad()
#     loss.backward()
#     optimizer.step()

In [26]:
import torchmetrics

# preds = torch.randn(10, 5).softmax(dim=-1)
# target = torch.randint(5, (10, ))

# acc = torchmetrics.functional.accuracy(preds, target)

In [27]:
# from torch.utils.tensorboard import SummaryWriter

# writer = SummaryWriter('./tensorboard')
# num_epoch = 10

# for epoch in range(num_epoch):
#     model.train()
#     batch_loss = 0.0

#     for i, (x,y) in enumerate(dataloader):